Homework 13 Haritonov Fedor
meFedron12/Python-Learning pull request #1
Opened 2023-04-05 21:41 UTC by meFedron12

2023-04-06 13:06 UTC, vimoro requested changes

2023-04-06 13:06 UTC, vimoro commented on dz13.py
молодец что разобрался и в пул реквесте только дз👍

2023-04-06 13:06 UTC, vimoro commented on dz13.py
> +        self.start_num = start_num
не понимаю, зачем тебе этот атрибут start_num

2023-04-06 13:06 UTC, vimoro commented on dz13.py
> +        if self.stop_iteration_num is not None and self.start_num > self.stop_iteration_num:
в задании просят `result` (который равен `random.randint(self.first_num, self.second_num)`) и `stop_iteration_num`, и если они равны, выбрасывать исключение

2023-04-06 13:06 UTC, vimoro commented on dz13.py
> +def randomize(Start_num, first_num: int = None, second_num: int = None, Stop_num: int = None):
почему `Stop_num` с большой буквы? это не по pep8

2023-04-06 13:06 UTC, vimoro commented on dz13.py
> +        print(random.randint(first_num, second_num))
принта в генераторе быть не должно, ты должен значение `random.randint(first_num, second_num)` отдавать в `yield`

2023-04-06 13:06 UTC, vimoro commented on dz13.py
> +        if Stop_num is not None and Start_num > Stop_num:
условие по остановке такое же, как и в комментарии к классу я написала

2023-04-06 16:49 UTC, meFedron12 reviewed
Вроде исправил

2023-04-07 11:05 UTC, vimoro approved these changes

2023-04-07 11:05 UTC, vimoro commented on dz13.py
> +        result += 1
вот эта стрчка лишняя

2023-04-07 11:05 UTC, vimoro commented on dz13.py
> +        result += 1
и эта лишняя

2023-04-07 11:05 UTC, vimoro commented on dz13.py
остальное все отлично, убери эти две строки и можешь мержить

2023-04-09 20:03 UTC, merged